<?php

namespace Brickrouge;

use ICanBoogie\ErrorCollection;

$errors = (new ErrorCollection)
	->add('input0', "The field <q>{label}</q> <code>{name}</code> is required.");

echo new Form([

	Element::CHILDREN => [

		'input0' => new Text([ Group::LABEL => 'Required', 'required' => true ]),
		'input1' => new Text([ Group::LABEL => 'Optional' ])

	],

	Form::ERRORS => $errors,
	Form::RENDERER => Form\GroupRenderer::class

]);
