<section id="forms">
	<h1>Forms</h1>

	<h2>Form controls</h2>

	<p>Creating a form is super easy with instances of <code>Form</code>, <code>Element</code>,
	<code>Text</code>, …</p>

	<?= render_example('examples/forms/controls') ?>

	<h2>Prepend &amp; append inputs</h2>
	<p><code>Text</code> inputs&mdash;with appended or prepended text&mdash;provide an easy way to give more
	context for your inputs. Great examples include the <code>@</code> sign for Twitter usernames or <code>€</code> for
	finances. The <code>ADDON</code> attribute defines the add-on text, the
	<code>ADDON_POSITION</code> attribute to define its position.</p>

	<?= render_example('examples/forms/addons') ?>
</section>
