<?php

namespace Brickrouge;

?>
<section id="buttonDropdowns">
	<h1>Split button dropdowns</h1>

	<p>Split buttons feature a standard action on the left and a dropdown toggle on the right with
	contextual links.</p>

	<p>Dropdown menu options are defined using the <code>OPTION</code> attribute, the same way
	options are defined for <code>select</code>, <code>TYPE_CHECKBOX_GROUP</code> or
	<code>TYPE_RADIO_GROUP</code> element, the twist is that <code>false</code> options are turned
	into separators.</p>

	<p>All <code>btn-*</code> class names are forwarded to the button elements, thus you can create
	a small primary split button with <code>btn-primary btn-sm</code>. The <code>disabled</code>
	class name is forwarded as well.</p>

	<div class="doc-example">
		<div class="form-group"><?php

		echo render_demo('examples/split-buttons/one');

		$options = [

			'Action',
			'Another action',
			'Something else here',
			false,
			'Separated link'

		];

		echo PHP_EOL;
		echo new SplitButton('Action', [ Element::OPTIONS => $options, 'class' => 'btn-primary' ]) . PHP_EOL;
		echo new SplitButton('Danger', [ Element::OPTIONS => $options, 'class' => 'btn-danger' ]) . PHP_EOL;
		echo new SplitButton('Success', [ Element::OPTIONS => $options, 'class' => 'btn-success' ]) . PHP_EOL;
		echo new SplitButton('Info', [ Element::OPTIONS => $options, 'class' => 'btn-info' ]) . PHP_EOL;
		echo new SplitButton('Default', [ Element::OPTIONS => $options ]) . PHP_EOL;

		?></div>

		<div class="form-group"><?php

			echo new SplitButton('Large success', [ Element::OPTIONS => $options, 'class' => 'btn-success btn-lg' ]) . PHP_EOL;
			echo new SplitButton('Small danger', [ Element::OPTIONS => $options, 'class' => 'btn-danger btn-sm' ]) . PHP_EOL;
			echo new SplitButton('Small disabled info', [ Element::OPTIONS => $options, 'class' => 'btn-info btn-sm disabled' ]) . PHP_EOL;

		?></div>
	</div>

	<?= render_source('examples/split-buttons/one') ?>

</section>
