<div class="container">
	<footer class="footer aside-muted">
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p>Developped by <a href="http://weirdog.com">Olivier Laviale</a>
		(<a href="http://twitter.com/olvlvl" target="_blank">@olvlvl</a>), leveraging the awesomeness
		of <a href="http://twitter.github.com/bootstrap/" target="_blank">Bootstrap</a>
		and <a href="http://mootools.net" target="_blank">MooTools</a>.</p>
		<p>Brickrouge is licensed under the <a href="http://en.wikipedia.org/wiki/BSD_licenses" target="_blank">Simplified BSD license</a>.</p>
	</footer>
</div>

<div class="github-fork-ribbon-wrapper top right">
	<div class="github-fork-ribbon">
		<a href="http://github.com/Brickrouge/Brickrouge" target="_blank">Fork me on GitHub</a>
	</div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js"></script>
<script type="text/javascript" src="<?= Brickrouge\Document::resolve_url(Brickrouge\ASSETS . 'brickrouge.js') ?>"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad()</script>

<script type="text/javascript">

$$('.dropdown-menu li').addEvent('click', function (ev) {
	ev.preventDefault()
})

<?php if (PHP_SAPI !== 'cli-server'): ?>

  var _gaq = _gaq || []

  _gaq.push(['_setAccount', 'UA-8673332-4'])
  _gaq.push(['_trackPageview'])

  !function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  } ()

<?php endif ?>

</script>

<script src="/assets/mootools-more.js" type="text/javascript"></script>
<script src="/assets/brickrouge/calendar.js" type="text/javascript"></script>

<script type="text/javascript">

	window.addEvent('domready', function() {

		new Brickrouge.Calendar('calendar-edit-date')

		var month = new Brickrouge.Calendar.Month('standalone-calendar-month', { noWeekNumber: true })
			, monthDebug = $('standalone-calendar-month-debug')

		month.addEvents({

			update: function(date) {

				monthDebug.innerHTML = '<strong>update:</strong> ' + date.format('%Y-%m-%d')

			},

			change: function(date) {

				monthDebug.innerHTML = '<strong>change:</strong> ' + date.format('%Y-%m-%d')

			}
		})

		/* calendar-placeholder */

		var calendar = Brickrouge.Calendar.from({ noWeekNumber: true, noDayNames: true })

		calendar.element.inject('calendar-placeholder')

		/* calendar-edit-month-year */

		new Brickrouge.Calendar('calendar-edit-month-year')

		/* popover */

		new Brickrouge.Datepicker({ anchor: 'calendar-anchor' })
	})

</script>
