<div class="container">
	<footer class="footer aside-muted">
		<p class="pull-right"><a href="#">Back to top</a></p>
		<p>Developped by <a href="http://weirdog.com">Olivier Laviale</a>
		(<a href="http://twitter.com/olvlvl" target="_blank">@olvlvl</a>), leveraging the awesomeness
		of <a href="http://twitter.github.com/bootstrap/" target="_blank">Bootstrap</a>
		and <a href="http://mootools.net" target="_blank">MooTools</a>.</p>
		<p>Brickrouge is licensed under the <a href="http://en.wikipedia.org/wiki/BSD_licenses" target="_blank">Simplified BSD license</a>.</p>
	</footer>
</div>

<div class="github-fork-ribbon-wrapper top right">
	<div class="github-fork-ribbon">
		<a href="http://github.com/Brickrouge/Brickrouge" target="_blank">Fork me on GitHub</a>
	</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js" type="text/javascript" ></script>
<script src="<?= Brickrouge\Document::resolve_url(Brickrouge\ASSETS . 'brickrouge.js') ?>" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.9.1/highlight.min.js" type="text/javascript"></script>

<script type="text/javascript">

	hljs.initHighlightingOnLoad()

	$$('.dropdown-menu li').addEvent('click', function (ev) {
		ev.preventDefault()
	})

	<?php if (PHP_SAPI !== 'cli-server'): ?>

	var _gaq = _gaq || []

	_gaq.push(['_setAccount', 'UA-8673332-4'])
	_gaq.push(['_trackPageview'])

	!function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	} ()

	<?php endif ?>

</script>
