<?php

namespace App;

use ICanBoogie\Routing\RouteDefinition as Route;

$app = \ICanBoogie\app();
$routes = $app->routes->filter(function(array $definition) {

	return isset($definition[Route::CONTROLLER]) && !empty($definition['title'])
	&& $definition[Route::CONTROLLER] === PageController::class;

});

$current_route = $app->request->context['route'];

?><nav class="navbar navbar-dark bg-inverse">
	<div class="container">
		<ul class="nav navbar-nav">
			<?php foreach ($routes as $id => $definition): ?>
			<li
				class="nav-item <?= $id == $current_route->id ? 'active' : '' ?>"><a
					href="<?= $definition[Route::PATTERN] ?>" class="nav-link"><?= $definition['title'] ?></a></li>
			<?php endforeach ?>
		</ul>
	</div>
</nav>
