<?php

namespace App;

?>

<div id="overview" class="hero-unit">
	<div class="container">
	<h1>Brick<span>rouge</span><small> from <a href="http://weirdog.com/" target="_blank" title="Olivier Laviale">me</a></small></h1>

	<div class="row">
		<div class="col-lg-9">
			<p class="lead">Brickrouge is an object-oriented toolkit for PHP5.5+ that
				helps you create inputs, widgets, forms and many other common elements, with
				all the CSS and JavaScript needed to make them beautiful and magical.</p>

			<div class="more">
				<p>Brickrouge uses
					<a href="http://twitter.github.com/bootstrap/" target="_blank">Bootstrap from twitter</a> for its style,
					and <a href="http://mootools.net">MooTools</a> for its magic. Ready in a minute,
					you'll have everything you need to create beautiful and clean UIs.</p>

				<p>Together with <a href="https://github.com/ICanBoogie/ICanBoogie/">ICanBoogie</a>, Brickrouge is one of the
					precious components that make the CMS <a href="http://icybee.org">Icybee</a>, but it
					remains a standalone project for everyone to enjoy!</p>
			</div>

			<ul class="quick-links aside-muted">
				<li><iframe src="https://ghbtns.com/github-btn.html?user=Brickrouge&repo=Brickrouge&type=star&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="80px" height="20px"></iframe></li>
				<li><iframe src="https://ghbtns.com/github-btn.html?user=Brickrouge&repo=Brickrouge&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="80px" height="20px"></iframe></li>
				<li><a href="https://github.com/Brickrouge/Brickrouge#readme" target="_blank">README</a></li>
				<li><a href="/docs">Autodoc</a></li>
				<li><a href="https://twitter.com/#!/olvlvl" target="_blank" title="Olivier Laviale sur Tweeter">@olvlvl</a></li>
			</ul>

		</div>

		<div class="col-lg-3 hidden-md-down">
			<div class="benefits aside-muted">
				<ul>
					<li><span>✓</span> Standalone and patchable</li>
					<li><span>✓</span> Compatible with Bootstrap</li>
					<li><span>✓</span> Support localization</li>
					<li><span>✓</span> Is a <a href="https://packagist.org/packages/brickrouge/brickrouge">Composer package</a></li>
					<li><span>✓</span> Object-oriented</li>
					<li><span>✓</span> Create any kind of element</li>
					<li><span>✓</span> Populate and validate forms</li>
				</ul>
			</div>
		</div>
	</div>
	</div>
</div>

<div class="container">

<?php require ROOT . 'protected/sections/getting-started.php' ?>
<?php //require ROOT . 'protected/sections/form.php' ?>
<?php require ROOT . 'protected/sections/forms.php' ?>
<?php require ROOT . 'protected/sections/groups.php' ?>
<?php require ROOT . 'protected/sections/popovers.php' ?>
<?php require ROOT . 'protected/sections/buttons.php' ?>
<?php require ROOT . 'protected/sections/splitbutton.php' ?>
<?php require ROOT . 'protected/sections/alerts.php' ?>

</div>
