<?php

namespace Brickrouge;

?>

<div class="hero-unit">
	<div class="container">
		<h1>Navigation</h1>

		<p></p>
	</div>
</div>

<section class="container">

	<div class="page-header">
		<h1>Tabs</h1>
	</div>

	<div class="tabbable">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link active" data-toggle="tab" href="#">Active</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" data-toggle="tab" href="#">Another link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" data-toggle="tab" href="#">Disabled</a>
			</li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane active">
				one
			</div>
			<div class="tab-pane">
				two
			</div>
			<div class="tab-pane">
				three
			</div>
			<div class="tab-pane">
				four
			</div>
		</div>
	</div>

</section>
