<section id="alerts">
	<h1>Alerts <small>Success, warning, and error messages</small></h1>

	<div class="row">
		<div class="col-lg-4">
			<h3>Error or danger</h3>
			<?= render_example('examples/alerts/danger') ?>
		</div>
		<div class="col-lg-4">
			<h3>Success</h3>
			<?= render_example('examples/alerts/success') ?>
		</div>
		<div class="col-lg-4">
			<h3>Information</h3>
			<?= render_example('examples/alerts/info') ?>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-4">
			<h3>Heading &amp; multi-line</h3>

			<p>Easily extend the standard alert message with two optional classes:
				<code>.alert-block</code> for more padding and text controls and
				<code>.alert-heading</code> for a matching heading.</p>
		</div>

		<div class="col-lg-8">
			<p>The <code>HEADING</code> attribute may be used to define a heading.</p>
			<?= render_example('examples/alerts/block') ?>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-4">
			<h3>Dismissible alerts</h3>
			<p>Alerts may be dismissible. If a dismissible alert is tied to a form when the alert
			is dismissed the errors of the form are dismissed as well.</p>
		</div>

		<div class="col-lg-8">
			<?= render_example('examples/alerts/dismissible') ?>
		</div>
	</div>

	<h2>Error collections</h2>

	<p>The <code>Alert</code> class can also render <code>ErrorCollection</code> instances.</p>
	<?= render_example('examples/alerts/errors') ?>
</section>
